[package]
name = "MFEKmetadata"
version = "0.0.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]
description = "Basic metadata fetcher for the MFEK project. It interrogates UFO fonts, for now mostly fontinfo.plist"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
norad = "0.4"
serde-value = "0.7.0"
enum_for_matches = "0.1.1"
unic-ucd = "0.9"
csv = "1.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
